import api from './api';

export const adminApi = {
  dashboardStats: () => api.get('/admin/dashboard/stats'),
  users: (params) => api.get('/admin/users', { params }),
  getReportingManagers: () => api.get('/admin/reporting-managers'),
  createUser: (payload) => api.post('/admin/users/create', payload),
  bulkImportUsers: (formData) =>
    api.post('/admin/users/bulk-import', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
  changeUserRole: (userId, role) => api.put(`/admin/users/${userId}/role`, { role }),
  deactivateUser: (userId) => api.delete(`/admin/users/${userId}`),
  updateUser: (userId, payload) => api.put(`/admin/users/${userId}`, payload),
  impactLevels: (params) => api.get('/admin/impact-levels', { params }),
  createImpactLevel: (payload) => api.post('/admin/impact-levels', payload),
  updateImpactLevel: (id, payload) => api.put(`/admin/impact-levels/${id}`, payload),
  deprecateImpactLevel: (id) => api.delete(`/admin/impact-levels/${id}`),
  cityGroups: () => api.get('/admin/city-groups'),
  createCityGroup: (payload) => api.post('/admin/city-groups', payload),
  updateCityGroup: (id, payload) => api.put(`/admin/city-groups/${id}`, payload),
  deleteCityGroup: (id) => api.delete(`/admin/city-groups/${id}`),
  expenseLimits: (params) => api.get('/admin/expense-limits', { params }),
  createExpenseLimit: (payload) => api.post('/admin/expense-limits', payload),
  updateExpenseLimit: (id, payload) => api.put(`/admin/expense-limits/${id}`, payload),
  deleteExpenseLimit: (id) => api.delete(`/admin/expense-limits/${id}`),
  policyVersions: () => api.get('/admin/policy-versions'),
  createPolicyVersion: (payload) => api.post('/admin/policy-versions', payload),
  submitPolicyVersion: (id) => api.post(`/admin/policy-versions/${id}/submit`),
  approvePolicyVersion: (id) => api.post(`/admin/policy-versions/${id}/approve`),
  diffPolicyVersions: (v1, v2) => api.get('/admin/policy-versions/diff', { params: { v1, v2 } }),
  expenseCategories: (params) => api.get('/admin/expense-categories', { params }),
  createExpenseCategory: (payload) => api.post('/admin/expense-categories', payload),
  updateExpenseCategory: (id, payload) => api.put(`/admin/expense-categories/${id}`, payload),
  deactivateExpenseCategory: (id) => api.delete(`/admin/expense-categories/${id}`),
  blacklistCheck: (payload) => api.post('/admin/expense-categories/blacklist-check', payload),
  companyProfile: () => api.get('/admin/company-profile'),
  updateCompanyProfile: (payload) => api.put('/admin/company-profile', payload),
  auditLogs: (params) => api.get('/audit/logs', { params }),
  auditLogsExport: (params) => api.get('/audit/logs/export', { params, responseType: 'blob' }),
  notificationTemplates: () => api.get('/notifications/templates'),
  updateNotificationTemplate: (id, payload) => api.put(`/notifications/templates/${id}`, payload),
  workflowConfig: () => api.get('/workflow/config'),
  updateWorkflowConfig: (config) => api.put('/workflow/config', { config }),
  holidays: () => api.get('/admin/holidays'),
  createHoliday: (payload) => api.post('/admin/holidays', payload),
  updateHoliday: (id, payload) => api.put(`/admin/holidays/${id}`, payload),
  deleteHoliday: (id) => api.delete(`/admin/holidays/${id}`),
};
