"""Add Delegation

Revision ID: 05fcd142afbf
Revises: 8645091570b2
Create Date: 2026-07-09 09:35:36.279639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fcd142afbf'
down_revision: Union[str, None] = '8645091570b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegatee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_delegatee_id'), 'delegations', ['delegatee_id'], unique=False)
    op.create_index(op.f('ix_delegations_delegator_id'), 'delegations', ['delegator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delegations_delegator_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_delegatee_id'), table_name='delegations')
    op.drop_table('delegations')
    # ### end Alembic commands ###
