"""add_multicity

Revision ID: 38d96bcddee2
Revises: 05fcd142afbf
Create Date: 2026-07-09 09:43:19.346992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38d96bcddee2'
down_revision: Union[str, None] = '05fcd142afbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_request_legs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travel_request_id', sa.Integer(), nullable=False),
    sa.Column('leg_sequence', sa.Integer(), nullable=False),
    sa.Column('travel_mode', sa.String(length=16), nullable=True),
    sa.Column('from_city', sa.String(length=128), nullable=False),
    sa.Column('to_city', sa.String(length=128), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['travel_request_id'], ['travel_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_request_legs_travel_request_id'), 'travel_request_legs', ['travel_request_id'], unique=False)
    op.add_column('travel_requests', sa.Column('trip_type', sa.String(length=24), nullable=False))
    op.alter_column('travel_requests', 'from_city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('travel_requests', 'to_city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('travel_requests', 'travel_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travel_requests', 'travel_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('travel_requests', 'to_city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('travel_requests', 'from_city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.drop_column('travel_requests', 'trip_type')
    op.drop_index(op.f('ix_travel_request_legs_travel_request_id'), table_name='travel_request_legs')
    op.drop_table('travel_request_legs')
    # ### end Alembic commands ###
