"""add_from_city_to_claim_draft

Revision ID: 810779e1fb2c
Revises: 0018_company_holidays
Create Date: 2026-05-14 12:45:17.676584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '810779e1fb2c'
down_revision: Union[str, None] = '0018_company_holidays'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advance_approval_stages', sa.Column('required_role', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_advance_approval_stages_required_role'), 'advance_approval_stages', ['required_role'], unique=False)
    op.add_column('claim_approval_stages', sa.Column('required_role', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_claim_approval_stages_required_role'), 'claim_approval_stages', ['required_role'], unique=False)
    op.add_column('claim_drafts', sa.Column('from_city', sa.String(length=128), nullable=True))
    op.alter_column('claim_drafts', 'status',
               existing_type=mysql.ENUM('DRAFT', 'PENDING_EXCEPTION', 'SUBMITTED', 'IN_APPROVAL', 'READY_FOR_PAYMENT', 'SENT_BACK', 'APPROVED', 'PAID', 'REJECTED', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('DRAFT', 'PENDING_EXCEPTION', 'SUBMITTED', 'IN_APPROVAL', 'READY_FOR_PAYMENT', 'SENT_BACK', 'REJECTED', 'ON_HOLD', 'PAID', name='claimstatus'),
               existing_nullable=False)
    op.drop_index(op.f('uq_claim_trips_claim_trip'), table_name='claim_trips')
    op.drop_constraint(op.f('claim_trips_ibfk_1'), 'claim_trips', type_='foreignkey')
    op.drop_constraint(op.f('claim_trips_ibfk_2'), 'claim_trips', type_='foreignkey')
    op.create_foreign_key(None, 'claim_trips', 'travel_trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'claim_trips', 'claim_drafts', ['claim_id'], ['id'])
    op.drop_index(op.f('uq_exception_approvals_req_role'), table_name='exception_approvals')
    op.drop_index(op.f('template_key'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_template_key'), table_name='notification_templates')
    op.create_index(op.f('ix_notification_templates_template_key'), 'notification_templates', ['template_key'], unique=True)
    op.alter_column('notifications', 'category',
               existing_type=mysql.ENUM('APPROVAL_REQUIRED', 'CLAIM_UPDATE', 'PAYMENT', 'SLA_BREACH', 'ADVANCE', 'EXCEPTION', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index(op.f('token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_travel_trips_travel_request_id'), 'travel_trips', ['travel_request_id'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_travel_trips_travel_request_id'), table_name='travel_trips')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('notifications', 'category',
               existing_type=sa.String(length=32),
               type_=mysql.ENUM('APPROVAL_REQUIRED', 'CLAIM_UPDATE', 'PAYMENT', 'SLA_BREACH', 'ADVANCE', 'EXCEPTION', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_templates_template_key'), table_name='notification_templates')
    op.create_index(op.f('ix_notification_templates_template_key'), 'notification_templates', ['template_key'], unique=False)
    op.create_index(op.f('template_key'), 'notification_templates', ['template_key'], unique=True)
    op.create_index(op.f('uq_exception_approvals_req_role'), 'exception_approvals', ['exception_request_id', 'required_role'], unique=True)
    op.drop_constraint(None, 'claim_trips', type_='foreignkey')
    op.drop_constraint(None, 'claim_trips', type_='foreignkey')
    op.create_foreign_key(op.f('claim_trips_ibfk_2'), 'claim_trips', 'travel_trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('claim_trips_ibfk_1'), 'claim_trips', 'claim_drafts', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_claim_trips_claim_trip'), 'claim_trips', ['claim_id', 'trip_id'], unique=True)
    op.alter_column('claim_drafts', 'status',
               existing_type=sa.Enum('DRAFT', 'PENDING_EXCEPTION', 'SUBMITTED', 'IN_APPROVAL', 'READY_FOR_PAYMENT', 'SENT_BACK', 'REJECTED', 'ON_HOLD', 'PAID', name='claimstatus'),
               type_=mysql.ENUM('DRAFT', 'PENDING_EXCEPTION', 'SUBMITTED', 'IN_APPROVAL', 'READY_FOR_PAYMENT', 'SENT_BACK', 'APPROVED', 'PAID', 'REJECTED', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('claim_drafts', 'from_city')
    op.drop_index(op.f('ix_claim_approval_stages_required_role'), table_name='claim_approval_stages')
    op.drop_column('claim_approval_stages', 'required_role')
    op.drop_index(op.f('ix_advance_approval_stages_required_role'), table_name='advance_approval_stages')
    op.drop_column('advance_approval_stages', 'required_role')
    # ### end Alembic commands ###
