"""add_image_hash_to_invoice

Revision ID: 8645091570b2
Revises: 9e14efab6f69
Create Date: 2026-07-08 14:37:06.545018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8645091570b2'
down_revision: Union[str, None] = '9e14efab6f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_invoices_image_hash'), 'invoices', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_image_hash'), table_name='invoices')
    op.drop_column('invoices', 'image_hash')
    # ### end Alembic commands ###
