"""Add LoginOTP table

Revision ID: 9e14efab6f69
Revises: a79b8e345eb4
Create Date: 2026-07-07 12:37:37.670730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e14efab6f69'
down_revision: Union[str, None] = 'a79b8e345eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_otps_id'), 'login_otps', ['id'], unique=False)
    op.create_index(op.f('ix_login_otps_user_id'), 'login_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_otps_user_id'), table_name='login_otps')
    op.drop_index(op.f('ix_login_otps_id'), table_name='login_otps')
    op.drop_table('login_otps')
    # ### end Alembic commands ###
